"""
Sample promotion cases for testing the FMCG Trade Promotion Intelligence system.
"""

SAMPLE_CASES = [
    {
        "promotion_id": "PROMO-2024-Q1-HEALTHY",
        "brand": "FreshBeverage Co",
        "category": "Beverages",
        "sku": "FB-ORANGE-1L",
        "channel": "Modern Trade",
        "key_account": "SuperMart Chain",
        "region": "Northeast",
        "promotion_period_start": "2024-01-15",
        "promotion_period_end": "2024-02-15",
        "campaign_objective": "Volume Growth",
        "promotion_type": "Price Discount 10%",
        "baseline_sales_volume": 80000,
        "promotion_sales_volume": 110000,
        "uplift_percent": 37.5,
        "key_account_contribution_percent": 32,
        "channel_contribution_percent": 45,
        "num_participating_customers": 1205,
        "sell_in_volume": 112000,
        "sell_out_volume": 108000,
        "post_promotion_demand": 85000,
        "repeat_order_behavior": {"repeat_rate": 0.72, "trend": "stable"},
        "inventory_impact": {"shelf_inventory_increase": "12%", "warehouse_buildup": False},
        "replenishment_issues": None,
        "forecast_variance": 4.2,
        "discount_percent": 10.0,
        "trade_spend": 35000,
        "gross_margin_before": 42.5,
        "gross_margin_during": 38.2,
        "management_notes": "Well-planned seasonal promotion. Good customer spread. Monitoring closely.",
        "data_quality_confidence": 92,
    },
    {
        "promotion_id": "PROMO-2024-Q1-FRAGILE",
        "brand": "SnackMasters Ltd",
        "category": "Snacks",
        "sku": "SM-CHIPS-150G",
        "channel": "Modern Trade",
        "key_account": "MegaStore Corp",
        "region": "Central",
        "promotion_period_start": "2024-01-20",
        "promotion_period_end": "2024-01-31",
        "campaign_objective": "Market Share Defense",
        "promotion_type": "Price Discount 20%",
        "baseline_sales_volume": 120000,
        "promotion_sales_volume": 198000,
        "uplift_percent": 65.0,
        "key_account_contribution_percent": 58,
        "channel_contribution_percent": 62,
        "num_participating_customers": 850,
        "sell_in_volume": 205000,
        "sell_out_volume": 165000,
        "post_promotion_demand": 95000,
        "repeat_order_behavior": {"repeat_rate": 0.38, "trend": "declining"},
        "inventory_impact": {"shelf_inventory_increase": "35%", "warehouse_buildup": True},
        "replenishment_issues": "High volatility in reorder patterns",
        "forecast_variance": 22.5,
        "discount_percent": 20.0,
        "trade_spend": 125000,
        "gross_margin_before": 35.0,
        "gross_margin_during": 18.5,
        "management_notes": "Competitor activity forcing aggressive action. Sales team pushing hard.",
        "data_quality_confidence": 78,
    },
    {
        "promotion_id": "PROMO-2024-Q1-DISTORTIONARY",
        "brand": "PremiumBeverage Inc",
        "category": "Beverages - Premium",
        "sku": "PB-PREMIUM-500ML",
        "channel": "Modern Trade",
        "key_account": "Premium Retailer A",
        "region": "Metro",
        "promotion_period_start": "2024-02-01",
        "promotion_period_end": "2024-02-14",
        "campaign_objective": "EOY Volume Push",
        "promotion_type": "Heavy Discount 25% + Trade Spend",
        "baseline_sales_volume": 45000,
        "promotion_sales_volume": 156000,
        "uplift_percent": 246.7,
        "key_account_contribution_percent": 78,
        "channel_contribution_percent": 72,
        "num_participating_customers": 145,
        "sell_in_volume": 160000,
        "sell_out_volume": 78000,
        "post_promotion_demand": 32000,
        "repeat_order_behavior": {"repeat_rate": 0.21, "trend": "sharply_declining"},
        "inventory_impact": {"shelf_inventory_increase": "68%", "warehouse_buildup": True},
        "replenishment_issues": "Excessive one-time orders. Normal replenishment delayed.",
        "forecast_variance": 48.3,
        "discount_percent": 25.0,
        "trade_spend": 285000,
        "gross_margin_before": 48.0,
        "gross_margin_during": 8.5,
        "management_notes": "Major retailer negotiated aggressively. Trade loading suspected.",
        "data_quality_confidence": 85,
    },
    {
        "promotion_id": "PROMO-2024-Q1-MISLEADING",
        "brand": "QuickMeal Foods",
        "category": "Prepared Foods",
        "sku": "QM-FROZEN-CURRY",
        "channel": "Modern Trade",
        "key_account": "Supermarket National",
        "region": "South",
        "promotion_period_start": "2024-01-10",
        "promotion_period_end": "2024-02-28",
        "campaign_objective": "Brand Repositioning",
        "promotion_type": "Multi-buy 2+1, Heavy Discount",
        "baseline_sales_volume": 35000,
        "promotion_sales_volume": 178000,
        "uplift_percent": 408.6,
        "key_account_contribution_percent": 85,
        "channel_contribution_percent": 68,
        "num_participating_customers": 89,
        "sell_in_volume": 182000,
        "sell_out_volume": 45000,
        "post_promotion_demand": 28000,
        "repeat_order_behavior": {"repeat_rate": 0.15, "trend": "collapsing"},
        "inventory_impact": {"shelf_inventory_increase": "95%", "warehouse_buildup": True},
        "replenishment_issues": "Critical: Sell-in 182K but sell-out only 45K. Massive gap.",
        "forecast_variance": 68.5,
        "discount_percent": 32.0,
        "trade_spend": 425000,
        "gross_margin_before": 40.2,
        "gross_margin_during": -8.5,
        "management_notes": "Flagship retailer negotiated record deal. Leadership celebrating numbers.",
        "data_quality_confidence": 88,
    },
]


def get_sample_case(case_type="healthy"):
    """Get a sample case by type: healthy, fragile, distortionary, misleading"""
    type_mapping = {
        "healthy": 0,
        "fragile": 1,
        "distortionary": 2,
        "misleading": 3,
    }
    idx = type_mapping.get(case_type.lower(), 0)
    return SAMPLE_CASES[idx] if idx < len(SAMPLE_CASES) else SAMPLE_CASES[0]


def get_all_sample_cases():
    """Get all sample cases"""
    return SAMPLE_CASES
