"""create core schema

Revision ID: f92e89c78761
Revises: 
Create Date: 2026-08-10 16:35:07.440631
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f92e89c78761'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COMMERCIAL_DIRECTOR', 'TRADE_MARKETING_REVIEWER', 'SALES_OPERATIONS_REVIEWER', 'COMMERCIAL_FINANCE_REVIEWER', 'CATEGORY_BRAND_REVIEWER', 'ACCOUNT_DISTRIBUTOR_REVIEWER', 'READ_ONLY_EXECUTIVE', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('upload_status', sa.Enum('UPLOADED', 'VALIDATING', 'VALID', 'VALID_WITH_WARNINGS', 'INVALID', 'ARCHIVED', name='dataset_status'), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('date_min', sa.Date(), nullable=True),
    sa.Column('date_max', sa.Date(), nullable=True),
    sa.Column('validation_summary_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_table('dataset_validation_issues',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('row_reference', sa.String(length=100), nullable=True),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('issue_message', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_validation_issues_dataset_id'), 'dataset_validation_issues', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_validation_issues_issue_code'), 'dataset_validation_issues', ['issue_code'], unique=False)
    op.create_table('diagnostic_cases',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=False),
    sa.Column('promotion_start_week', sa.Date(), nullable=False),
    sa.Column('promotion_end_week', sa.Date(), nullable=False),
    sa.Column('forecast_horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DATA_VALIDATION', 'READY_FOR_FORECAST', 'FORECASTING', 'INTERPRETING', 'INVESTIGATION_PENDING', 'READY_FOR_REVIEW', 'UNDER_HUMAN_REVIEW', 'COMPLETED', 'REJECTED', 'FAILED', name='case_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_cases_status'), 'diagnostic_cases', ['status'], unique=False)
    op.create_table('weekly_fmcg_sales',
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('sku_id', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.String(length=150), nullable=False),
    sa.Column('region', sa.String(length=150), nullable=False),
    sa.Column('sell_out_units', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('sell_in_units', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('promo_flag', sa.Boolean(), nullable=False),
    sa.Column('discount_depth', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('net_sales_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('gross_sales_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('gross_margin', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('stock_on_hand', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('out_of_stock_flag', sa.Boolean(), nullable=False),
    sa.Column('returns_units', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('source_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'sku_id', 'channel', 'region', name='uq_weekly_series_grain')
    )
    op.create_index('ix_weekly_series_scope', 'weekly_fmcg_sales', ['sku_id', 'channel', 'region', 'week_start_date'], unique=False)
    op.create_table('baseline_calculations',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_method', sa.String(length=100), nullable=False),
    sa.Column('baseline_start_week', sa.Date(), nullable=False),
    sa.Column('baseline_end_week', sa.Date(), nullable=False),
    sa.Column('baseline_values_json', sa.JSON(), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('quality_notes_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseline_calculations_diagnostic_case_id'), 'baseline_calculations', ['diagnostic_case_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sa.String(length=100), nullable=False),
    sa.Column('observed_outcome_json', sa.JSON(), nullable=False),
    sa.Column('classification_correct', sa.Boolean(), nullable=True),
    sa.Column('simulation_useful', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_events_diagnostic_case_id'), 'feedback_events', ['diagnostic_case_id'], unique=False)
    op.create_table('forecast_runs',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('adapter_name', sa.String(length=100), nullable=False),
    sa.Column('adapter_version', sa.String(length=100), nullable=False),
    sa.Column('forecast_target', sa.String(length=100), nullable=False),
    sa.Column('series_id', sa.String(length=500), nullable=False),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_diagnostic_case_id'), 'forecast_runs', ['diagnostic_case_id'], unique=False)
    op.create_index(op.f('ix_forecast_runs_run_status'), 'forecast_runs', ['run_status'], unique=False)
    op.create_table('growth_quality_assessments',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_status', sa.String(length=50), nullable=False),
    sa.Column('growth_signal_summary', sa.Text(), nullable=False),
    sa.Column('growth_quality_judgment', sa.Text(), nullable=False),
    sa.Column('primary_risk_class', sa.String(length=100), nullable=False),
    sa.Column('secondary_risk_classes_json', sa.JSON(), nullable=False),
    sa.Column('interpretation_evidence_json', sa.JSON(), nullable=False),
    sa.Column('uncertainty_notes_json', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_quality_assessments_diagnostic_case_id'), 'growth_quality_assessments', ['diagnostic_case_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'VALIDATED', 'VALIDATED_WITH_CHANGES', 'MORE_EVIDENCE_REQUIRED', 'REJECTED', name='review_status'), nullable=False),
    sa.Column('validated_risk_class', sa.String(length=100), nullable=True),
    sa.Column('reviewer_comments', sa.Text(), nullable=True),
    sa.Column('requested_evidence_json', sa.JSON(), nullable=False),
    sa.Column('final_decision_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_diagnostic_case_id'), 'human_reviews', ['diagnostic_case_id'], unique=False)
    op.create_table('decision_simulations',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('option', sa.String(length=100), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('potential_benefits_json', sa.JSON(), nullable=False),
    sa.Column('potential_risks_json', sa.JSON(), nullable=False),
    sa.Column('evidence_requirements_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['growth_quality_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_simulations_diagnostic_case_id'), 'decision_simulations', ['diagnostic_case_id'], unique=False)
    op.create_table('executive_outputs',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('output_version', sa.String(length=100), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('output_markdown', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('human_review_status', sa.Enum('PENDING', 'VALIDATED', 'VALIDATED_WITH_CHANGES', 'MORE_EVIDENCE_REQUIRED', 'REJECTED', name='review_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['growth_quality_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_outputs_diagnostic_case_id'), 'executive_outputs', ['diagnostic_case_id'], unique=False)
    op.create_table('forecast_evidence',
    sa.Column('forecast_run_id', sa.Uuid(), nullable=False),
    sa.Column('forecast_target', sa.String(length=100), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=500), nullable=False),
    sa.Column('forecast_direction', sa.String(length=50), nullable=False),
    sa.Column('forecasted_values_json', sa.JSON(), nullable=False),
    sa.Column('confidence_interval_json', sa.JSON(), nullable=False),
    sa.Column('baseline_comparison', sa.String(length=50), nullable=False),
    sa.Column('post_promo_retention_status', sa.String(length=50), nullable=False),
    sa.Column('decay_signal', sa.String(length=50), nullable=False),
    sa.Column('uncertainty_level', sa.String(length=50), nullable=False),
    sa.Column('data_quality_notes_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_evidence_forecast_run_id'), 'forecast_evidence', ['forecast_run_id'], unique=False)
    op.create_table('investigation_plans',
    sa.Column('diagnostic_case_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('investigation_items_json', sa.JSON(), nullable=False),
    sa.Column('recommended_owner', sa.String(length=100), nullable=False),
    sa.Column('decision_affected', sa.Text(), nullable=False),
    sa.Column('acting_too_early_risks_json', sa.JSON(), nullable=False),
    sa.Column('evidence_confidence', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['growth_quality_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostic_case_id'], ['diagnostic_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_plans_diagnostic_case_id'), 'investigation_plans', ['diagnostic_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_plans_diagnostic_case_id'), table_name='investigation_plans')
    op.drop_table('investigation_plans')
    op.drop_index(op.f('ix_forecast_evidence_forecast_run_id'), table_name='forecast_evidence')
    op.drop_table('forecast_evidence')
    op.drop_index(op.f('ix_executive_outputs_diagnostic_case_id'), table_name='executive_outputs')
    op.drop_table('executive_outputs')
    op.drop_index(op.f('ix_decision_simulations_diagnostic_case_id'), table_name='decision_simulations')
    op.drop_table('decision_simulations')
    op.drop_index(op.f('ix_human_reviews_diagnostic_case_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_growth_quality_assessments_diagnostic_case_id'), table_name='growth_quality_assessments')
    op.drop_table('growth_quality_assessments')
    op.drop_index(op.f('ix_forecast_runs_run_status'), table_name='forecast_runs')
    op.drop_index(op.f('ix_forecast_runs_diagnostic_case_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_index(op.f('ix_feedback_events_diagnostic_case_id'), table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index(op.f('ix_baseline_calculations_diagnostic_case_id'), table_name='baseline_calculations')
    op.drop_table('baseline_calculations')
    op.drop_index('ix_weekly_series_scope', table_name='weekly_fmcg_sales')
    op.drop_table('weekly_fmcg_sales')
    op.drop_index(op.f('ix_diagnostic_cases_status'), table_name='diagnostic_cases')
    op.drop_table('diagnostic_cases')
    op.drop_index(op.f('ix_dataset_validation_issues_issue_code'), table_name='dataset_validation_issues')
    op.drop_index(op.f('ix_dataset_validation_issues_dataset_id'), table_name='dataset_validation_issues')
    op.drop_table('dataset_validation_issues')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.execute('DROP TYPE IF EXISTS review_status')
    op.execute('DROP TYPE IF EXISTS case_status')
    op.execute('DROP TYPE IF EXISTS dataset_status')
    op.execute('DROP TYPE IF EXISTS user_role')
    # ### end Alembic commands ###
